agent_name: yoti_org
author: fetchai
version: 0.1.0
license: Apache-2.0
description: An AEA to represent an organisation registered with Yoti
aea_version: '>=0.9.0, <0.10.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/http_server:0.15.0
- fetchai/soef:0.15.0
- fetchai/yoti:0.1.0
contracts: []
protocols:
- fetchai/default:0.11.0
- fetchai/http:0.11.0
- fetchai/oef_search:0.12.0
- fetchai/signing:0.9.0
- fetchai/state_update:0.9.0
- fetchai/yoti:0.1.0
skills:
- fetchai/error:0.11.0
- fetchai/yoti_org:0.1.0
default_connection: fetchai/soef:any
default_ledger: fetchai
default_routing:
  fetchai/http:0.10.0: fetchai/http_server:0.15.0
  fetchai/yoti:0.1.0: fetchai/yoti:0.1.0
  fetchai/oef_search:0.11.0: fetchai/soef:0.15.0
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
registry_path: ../packages
---
public_id: fetchai/http_server:0.15.0
type: connection
config:
  api_spec_path: null
---
public_id: fetchai/yoti:0.1.0
type: connection
config:
  yoti_client_sdk_id: ${YOTI_CLIENT_SDK_ID}
  yoti_key_file_path: ${YOTI_KEY_FILE_PATH}
---
public_id: fetchai/yoti_org:0.1.0
type: skill
models:
  parameters:
    args:
      yoti_scenario_id: ${YOTI_SCENARIO_ID}
      yoti_client_sdk_id: ${YOTI_CLIENT_SDK_ID}
