agent_name: yoti_org
author: fetchai
version: 0.1.0
license: Apache-2.0
description: 'An AEA to represent an organisation registered with Yoti'
aea_version: ">=0.7.0, < 0.8.0"
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/p2p_libp2p:0.12.0
- fetchai/soef:0.12.0
contracts: []
protocols:
- fetchai/default:0.9.0
- fetchai/oef_search:0.10.0
- fetchai/signing:0.7.0
- fetchai/state_update:0.7.0
skills:
- fetchai/error:0.9.0
- fetchai/yoti_org:0.1.0
default_connection: fetchai/p2p_libp2p:any
default_ledger: fetchai
default_routing:
  fetchai/oef_search:0.10.0: fetchai/soef:0.12.0
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
registry_path: ../packages
