agent_name: yoti_user
author: fetchai
version: 0.1.0
license: Apache-2.0
description: 'An AEA to represent a user registered with Yoti'
aea_version: '>=0.8.0, <0.9.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/p2p_libp2p:0.13.0
- fetchai/soef:0.14.0
contracts: []
protocols:
- fetchai/default:0.10.0
- fetchai/oef_search:0.11.0
- fetchai/signing:0.8.0
- fetchai/state_update:0.8.0
skills:
- fetchai/error:0.10.0
- fetchai/yoti_user:0.1.0
default_connection: fetchai/p2p_libp2p:any
default_ledger: fetchai
default_routing:
  fetchai/oef_search:0.10.0: fetchai/soef:0.14.0
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
registry_path: ../packages
